version: '3.9'

services:
  nginx:
    image: nginx:alpine3.18
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  apache1:
    image: httpd:alpine3.18
    restart: always
    volumes:
      - ./apache1.html:/usr/local/apache2/htdocs/index.html:ro

  apache2:
    image: httpd:alpine3.18
    restart: always
    volumes:
      - ./apache2.html:/usr/local/apache2/htdocs/index.html:ro
